# Configuracion de desarrollo (Local)
app.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

# Correo de destino
app.contact.to-email=${APP_CONTACT_TO_EMAIL:keshratamaldonado@gmail.com}

# Base de datos H2 (Local file)
spring.datasource.url=jdbc:h2:file:./data/portfolio_db;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Configuracion Mail (Gmail real)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:keshratamaldonado@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:juzhxobgboufqpjx}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true
