# Configuracion de Produccion (Heroku/Render/AWS/Azure)
app.allowed-origins=${APP_ALLOWED_ORIGINS}

# Correo de destino
app.contact.to-email=${APP_CONTACT_TO_EMAIL}

# Base de datos H2 (Azure Persistent Storage)
# En Azure App Service Linux, /home es persistente
spring.datasource.url=jdbc:h2:file:/home/data/portfolio_db;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=${APP_DB_USER:sa}
spring.datasource.password=${APP_DB_PASSWORD:}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configuracion Mail
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

# Deshabilitar dev-tools si se usan
spring.devtools.add-properties=false
